name: Deploy Vue app to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.11.1
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # Use 'secrets' for secrets and 'vars' for variables
          EMAIL_PUBLIC_KEY: ${{ vars.EMAIL_PUBLIC_KEY }}
          EMAIL_SERVICE_ID: ${{ vars.EMAIL_SERVICE_ID }}
          EMAIL_TEMPLATE_ID: ${{ vars.EMAIL_TEMPLATE_ID }}
        # For Vue CLI, "npm run build" also works
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
